POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imx1bHVoIiwiaWQiOiI2NjVkYWJkMTRlYWY5YzQzMWYyY2YzNDQiLCJpYXQiOjE3MTgwMzg5NjN9.ju5-DLe5TQ-yn26PRgosZBYjMXK-GouCf1G-SpQN4Pk

{"title": "NewChem",
 "author": "SP",
 "url": "http://localhost:3003/api/blogs/newchem",
 "likes": 0,
 "userId": "665dabd14eaf9c431f2cf344"
}

